django/film/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('director/<pk>', views.DirectorDetail.as_view(), name='detalle_director'),
    path('film/<pk>', views.FilmDetail.as_view(), name='detalle_film'),
]

django/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('film/', include('film.urls'))
]

django/film/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Director(models.Model):
    name = models.CharField(max_length=150,help_text="Nombre completo del director")
    day_of_birth = models.DateField(null=True, blank=True)
    day_of_death = models.DateField(null=True, blank=True)
    image = models.URLField(null=True)
   
    def __str__(self):
        return '%s' % (self.name)

class Film(models.Model):
    title = models.CharField(max_length=150, help_text="Nombre de la película")
    release_date = models.DateField(null=True, blank=True)
    director = models.ForeignKey('Director', on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True, help_text="Descripción de la película")
    image = models.URLField(null=True)

    def __str__(self):
        return self.title

django/film/views.py
from django.shortcuts import render
from django.views import generic
from .models import *

class IndexView(generic.ListView):
    template_name = 'index.html'
    model = Director

class DirectorDetail(generic.DetailView):
    template_name = 'director.html'
    model = Director

class FilmDetail(generic.DetailView):
    template_name = 'film.html'
    model = Film

django/film/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Document</title>{% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</head>
<body>
    
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-10">
            {% block content %}{% endblock %}
        </div>

    </div>
</div>

</body>
</html>

django/film/templates/director.html
{% extends "base_generic.html" %}

{% block title %}<title>{{ director }}</title>{% endblock %}

{% block content %}
<h3>{{ director }}</h3>
<img src="{{ director.image }}" height="300"><br>
Fecha de nacimiento: {{ director.day_of_birth }}<br>
Fecha de defunción: {{ director.day_of_death }}<br>

<br>
<strong>Peliculas</strong><br>
<ul>
    {% for film in director.film_set.all %}
        <li><a href="../film/{{ film.id }}">{{ film }}</a></li>
    {% empty %}
        <li>No hay Peliculas</li>
    {% endfor %}
</ul>


{% endblock %}

django/film/templates/film.html
{% extends "base_generic.html" %}

{% block title %}<title>{{ film }}</title>{% endblock %}

{% block content %}
<h3>{{ film }}</h3>
<img src="{{ film.image }}" alt="{{ film }}" height="100"><br>
Fecha de estreno: {{ film.release_date }}<br>
<p>{{ film.description | linebreaks }}</p>


{% endblock %}

django/film/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Listado Directores</title>{% endblock %}

{% block content %}
<h3>Filmography</h3>

<ul>
    {% for director in object_list %}
        <li><a href="director/{{ director.id }}">{{ director }}</a></li>
    {% empty %}
        <li>No hay Directores</li>
    {% endfor %}
</ul>


{% endblock %}